### ISSUE TITLE
[osm] Joomla! currently powers over 3% of the entire internet and around 7% of all content managed websites

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/opensourcematters.org#10]
> Joomla! currently powers over 3% of the entire internet and around 7% of all content managed websites

These figures need updating on the https://www.opensourcematters.org homepage as they are factually inaccurate and misleading. 

I suggest 

"Joomla! currently powers over 2.1% of the entire internet and around 3.3% of all content managed websites"

source: https://w3techs.com/technologies/details/cm-joomla

**Comment by anibalsanchez** [comment]
Or.... it is a good opportunity to change to Value-Based Copywriting.
 
Numbers were fine 10 years ago. But, now it looks like it is better to sell based on the perceived value of the solution.

**Comment by Ayushi271** [comment]
Hello
Is this issue still open?
Can I work on this issue?

**Comment by PhilETaylor** [comment]
The figures are even worse now

Joomla is used by 2.6% of all the websites whose content management system we know. This is 1.7% of all websites.

**Comment by Ayushi271** [comment]
So can i  work on this and replace the previous values

**Comment by PhilETaylor** [comment]
The source code of the https://www.opensourcematters.org/ is not available in any repo and therefore it is not possible for the public to work on its content. 

The site can only be administered by those with administrator permissions for the Joomla installation on https://www.opensourcematters.org/

**Comment by Ayushi271** [comment]
Oh Okk Thanks for the information
